"""add skill_evidence, ai_extraction_records, and unknown_skill_reviews

Revision ID: 3eb327b2bdb9
Revises: e0762fa7d3b0
Create Date: 2026-09-17 15:23:58.364946

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3eb327b2bdb9'
down_revision = 'e0762fa7d3b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_extraction_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('source_type', sa.String(length=50), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('prompt_version', sa.String(length=50), nullable=True),
    sa.Column('latency_ms', sa.Float(), nullable=True),
    sa.Column('token_usage', sa.Integer(), nullable=True),
    sa.Column('skills_extracted_count', sa.Integer(), nullable=True),
    sa.Column('unknown_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_extraction_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_extraction_records_student_id'), ['student_id'], unique=False)

    op.create_table('skill_evidence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=True),
    sa.Column('raw_term', sa.String(length=150), nullable=False),
    sa.Column('evidence_type', sa.String(length=50), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('evidence_span', sa.Text(), nullable=True),
    sa.Column('section', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('skill_evidence', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_skill_evidence_student_id'), ['student_id'], unique=False)

    op.create_table('unknown_skill_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('raw_term', sa.String(length=150), nullable=False),
    sa.Column('context_snippet', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('suggested_canonical_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.ForeignKeyConstraint(['suggested_canonical_id'], ['skills.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('unknown_skill_reviews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_unknown_skill_reviews_student_id'), ['student_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('unknown_skill_reviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_unknown_skill_reviews_student_id'))

    op.drop_table('unknown_skill_reviews')
    with op.batch_alter_table('skill_evidence', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_skill_evidence_student_id'))

    op.drop_table('skill_evidence')
    with op.batch_alter_table('ai_extraction_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_extraction_records_student_id'))

    op.drop_table('ai_extraction_records')
    # ### end Alembic commands ###
