"""add recommendation_runs table

Revision ID: bb789ea167b4
Revises: 3eb327b2bdb9
Create Date: 2026-09-17 15:39:24.410907

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb789ea167b4'
down_revision = '3eb327b2bdb9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recommendation_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('job_role_id', sa.Integer(), nullable=True),
    sa.Column('weights_used', sa.JSON(), nullable=False),
    sa.Column('total_recommendations', sa.Integer(), nullable=True),
    sa.Column('recommendations_snapshot', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['job_role_id'], ['job_roles.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recommendation_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recommendation_runs_student_id'), ['student_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recommendation_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recommendation_runs_student_id'))

    op.drop_table('recommendation_runs')
    # ### end Alembic commands ###
