"""add explanation and evidence fields to skill_gaps

Revision ID: e0762fa7d3b0
Revises: ef7dd94f6228
Create Date: 2026-09-17 15:03:43.669410

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0762fa7d3b0'
down_revision = 'ef7dd94f6228'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('skill_gaps', schema=None) as batch_op:
        batch_op.add_column(sa.Column('evidence_summary', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('evidence_factor', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('explanation', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('skill_gaps', schema=None) as batch_op:
        batch_op.drop_column('explanation')
        batch_op.drop_column('evidence_factor')
        batch_op.drop_column('evidence_summary')

    # ### end Alembic commands ###
